-- Adds a per-colour "style note" so each variant's PDP has genuinely
-- different visible content, not just a different <title>/meta tag.
-- Google was showing most colour-variant URLs as "Discovered - currently
-- not indexed" because, with the same on-page description across colours,
-- they read as near-duplicate pages competing with each other.
--
-- See lib/variant-seo-content.ts for the generator that fills this in
-- automatically when left blank, and app/product/[slug]/product-detail.tsx
-- for where it's rendered (Description tab).

alter table product_variants
  add column if not exists style_note text;

comment on column product_variants.style_note is
  'Unique on-page paragraph for this colour (styling tip / occasion note), rendered in the PDP Description tab so each colour''s visible content differs from its siblings for SEO. Auto-generated by lib/variant-seo-content.ts when left blank; editable per variant in the admin panel.';
